model = "gpt-5.3-codex"
model_reasoning_effort = "medium"
sandbox_mode = "workspace-write"
projects = { "/home/see2et/.config/nvim" = { trust_level = "trusted" }, "/home/see2et/.codex" = { trust_level = "trusted" } }
web_search_request = true

[sandbox_workspace_write]
network_access = true

[features]
skills = true

[mcp_servers.serena]
command = "uvx"
args = [
    "--from",
    "git+https://github.com/oraios/serena",
    "serena-mcp-server",
    "--context",
    "codex",
    "--enable-web-dashboard",
    "false",
]

[mcp_servers.context7]
args = ["-y", "@upstash/context7-mcp"]
command = "npx"

# [mcp_servers.github]
# command = "~/.codex/github-mcp.sh"

# [mcp_servers.spec-workflow]
# command = "npx"
# args = [
#     "-y",
#     "@pimzino/spec-workflow-mcp@latest",
#     "~/repos/github.com/See2et/bakopa-vr",
#     "--AutoStartDashboard",
# ]

# [mcp_servers.UnityMCP]
# command = "cmd.exe"
# args = [
#     "/c",
#     "cd",
#     "/d",
#     "C:\\Users\\See2et\\AppData\\Local\\UnityMCP\\UnityMcpServer\\src",
#     "&&",
#     "uv",
#     "run",
#     "server.py",
# ]
